### ISSUE TITLE
!ROADMAP!

### ISSUE THREAD

**Issue by UCDNJJ** [AllenInstitute/sciduck#2]
## Near-term
- [x] #3
- [x] #4
- [ ] #5
- [x] #10
- [x] #11

## New Features
- [ ] [Visualization functions of quality control metrics](https://github.com/AllenInstitute/sciduck/issues/1)

## New recording
- [x] #6
- [x] #7
- [ ] #8

**Comment by UCDNJJ** [comment]
- [ ] Modify module names to follow scanpy via __init__.py. sciduck.qc, sciduck.metrics, sciduck.anno.

**Comment by UCDNJJ** [comment]
- [ ] Templates for constraints.
